/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ebX1a64hdCb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Card } from "@/components/ui/card"

export function NotesTaker() {
  return (
    (<div className="flex flex-col h-screen">
      <header
        className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">Todo App</h1>
        <Popover>
          <PopoverTrigger asChild>
            <Button size="sm" variant="primary">
              <PlusIcon className="w-4 h-4 mr-2" />
              Add Task
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-[400px] p-4 space-y-4">
            <div className="space-y-2">
              <Label htmlFor="task-title">Task Title</Label>
              <Input id="task-title" placeholder="Enter task title" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="task-description">Task Description</Label>
              <Textarea
                className="min-h-[100px]"
                id="task-description"
                placeholder="Enter task description" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="task-category">Task Category</Label>
              <div className="flex items-center gap-2">
                <Select id="task-category">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select category" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="design">Design</SelectItem>
                    <SelectItem value="writing">Writing</SelectItem>
                    <SelectItem value="finance">Finance</SelectItem>
                    <SelectItem value="engineering">Engineering</SelectItem>
                  </SelectContent>
                </Select>
                <Input className="w-full" id="new-category" placeholder="Add new category" />
              </div>
            </div>
            <div className="flex justify-end gap-2">
              <div>
                <Button variant="outline">Cancel</Button>
              </div>
              <Button>Add Task</Button>
            </div>
          </PopoverContent>
        </Popover>
      </header>
      <main className="flex-1 p-6 overflow-auto">
        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <Card
            className="p-4 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800">
            <div className="flex items-center justify-between mb-2">
              <Checkbox id="task-1" />
              <span className="text-xs text-gray-500 dark:text-gray-400">Created 2 days ago</span>
            </div>
            <h3 className="text-lg font-medium mb-1">Finish design mockups</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Complete the high-fidelity designs for the new homepage.
            </p>
            <div className="flex items-center justify-between">
              <span
                className="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium dark:bg-blue-900 dark:text-blue-100">
                Design
              </span>
              <div className="flex gap-2">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button size="icon" variant="ghost">
                      <DeleteIcon className="w-4 h-4" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[400px] p-4 space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="task-title">Task Title</Label>
                      <Input id="task-title" placeholder="Enter task title" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-description">Task Description</Label>
                      <Textarea
                        className="min-h-[100px]"
                        id="task-description"
                        placeholder="Enter task description" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-category">Task Category</Label>
                      <div className="flex items-center gap-2">
                        <Select id="task-category">
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="design">Design</SelectItem>
                            <SelectItem value="writing">Writing</SelectItem>
                            <SelectItem value="finance">Finance</SelectItem>
                            <SelectItem value="engineering">Engineering</SelectItem>
                          </SelectContent>
                        </Select>
                        <Input className="w-full" id="new-category" placeholder="Add new category" />
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <div>
                        <Button variant="outline">Cancel</Button>
                      </div>
                      <Button>Save Changes</Button>
                    </div>
                  </PopoverContent>
                </Popover>
                <Button
                  className="hover:text-red-500 dark:hover:text-red-500"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
          <Card
            className="p-4 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800">
            <div className="flex items-center justify-between mb-2">
              <Checkbox id="task-2" />
              <span className="text-xs text-gray-500 dark:text-gray-400">Created 1 week ago</span>
            </div>
            <h3 className="text-lg font-medium mb-1">Write blog post</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Prepare an outline and draft the new blog post on design trends.
            </p>
            <div className="flex items-center justify-between">
              <span
                className="px-2 py-1 bg-green-100 text-green-800 rounded-full text-xs font-medium dark:bg-green-900 dark:text-green-100">
                Writing
              </span>
              <div className="flex gap-2">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button size="icon" variant="ghost">
                      <DeleteIcon className="w-4 h-4" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[400px] p-4 space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="task-title">Task Title</Label>
                      <Input id="task-title" placeholder="Enter task title" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-description">Task Description</Label>
                      <Textarea
                        className="min-h-[100px]"
                        id="task-description"
                        placeholder="Enter task description" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-category">Task Category</Label>
                      <div className="flex items-center gap-2">
                        <Select id="task-category">
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="design">Design</SelectItem>
                            <SelectItem value="writing">Writing</SelectItem>
                            <SelectItem value="finance">Finance</SelectItem>
                            <SelectItem value="engineering">Engineering</SelectItem>
                          </SelectContent>
                        </Select>
                        <Input className="w-full" id="new-category" placeholder="Add new category" />
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <div>
                        <Button variant="outline">Cancel</Button>
                      </div>
                      <Button>Save Changes</Button>
                    </div>
                  </PopoverContent>
                </Popover>
                <Button
                  className="hover:text-red-500 dark:hover:text-red-500"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
          <Card
            className="p-4 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800">
            <div className="flex items-center justify-between mb-2">
              <Checkbox defaultChecked id="task-3" />
              <span className="text-xs text-gray-500 dark:text-gray-400">Created 3 days ago</span>
            </div>
            <h3 className="text-lg font-medium mb-1">Prepare quarterly report</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Gather data and compile the Q3 financial report for the team.
            </p>
            <div className="flex items-center justify-between">
              <span
                className="px-2 py-1 bg-yellow-100 text-yellow-800 rounded-full text-xs font-medium dark:bg-yellow-900 dark:text-yellow-100">
                Finance
              </span>
              <div className="flex gap-2">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button size="icon" variant="ghost">
                      <DeleteIcon className="w-4 h-4" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[400px] p-4 space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="task-title">Task Title</Label>
                      <Input id="task-title" placeholder="Enter task title" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-description">Task Description</Label>
                      <Textarea
                        className="min-h-[100px]"
                        id="task-description"
                        placeholder="Enter task description" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-category">Task Category</Label>
                      <div className="flex items-center gap-2">
                        <Select id="task-category">
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="design">Design</SelectItem>
                            <SelectItem value="writing">Writing</SelectItem>
                            <SelectItem value="finance">Finance</SelectItem>
                            <SelectItem value="engineering">Engineering</SelectItem>
                          </SelectContent>
                        </Select>
                        <Input className="w-full" id="new-category" placeholder="Add new category" />
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <div>
                        <Button variant="outline">Cancel</Button>
                      </div>
                      <Button>Save Changes</Button>
                    </div>
                  </PopoverContent>
                </Popover>
                <Button
                  className="hover:text-red-500 dark:hover:text-red-500"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
          <Card
            className="p-4 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800">
            <div className="flex items-center justify-between mb-2">
              <Checkbox id="task-4" />
              <span className="text-xs text-gray-500 dark:text-gray-400">Created 5 days ago</span>
            </div>
            <h3 className="text-lg font-medium mb-1">Implement new payment gateway</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Integrate the new payment processor into the checkout flow.
            </p>
            <div className="flex items-center justify-between">
              <span
                className="px-2 py-1 bg-purple-100 text-purple-800 rounded-full text-xs font-medium dark:bg-purple-900 dark:text-purple-100">
                Engineering
              </span>
              <div className="flex gap-2">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button size="icon" variant="ghost">
                      <DeleteIcon className="w-4 h-4" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-[400px] p-4 space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="task-title">Task Title</Label>
                      <Input id="task-title" placeholder="Enter task title" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-description">Task Description</Label>
                      <Textarea
                        className="min-h-[100px]"
                        id="task-description"
                        placeholder="Enter task description" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="task-category">Task Category</Label>
                      <div className="flex items-center gap-2">
                        <Select id="task-category">
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select category" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="design">Design</SelectItem>
                            <SelectItem value="writing">Writing</SelectItem>
                            <SelectItem value="finance">Finance</SelectItem>
                            <SelectItem value="engineering">Engineering</SelectItem>
                          </SelectContent>
                        </Select>
                        <Input className="w-full" id="new-category" placeholder="Add new category" />
                      </div>
                    </div>
                    <div className="flex justify-end gap-2">
                      <div>
                        <Button variant="outline">Cancel</Button>
                      </div>
                      <Button>Save Changes</Button>
                    </div>
                  </PopoverContent>
                </Popover>
                <Button
                  className="hover:text-red-500 dark:hover:text-red-500"
                  size="icon"
                  variant="ghost">
                  <TrashIcon className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </main>
    </div>)
  );
}

function DeleteIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
